// Notes appear according to date specified.
const notes = [
  // {
  //   folder:'folder-name',
  //   date: 'YYYY-MM-DD',
  //   title: 'Note Title',
  //   description: 'Description of the note.',
  //   thumbnail: false,
  //   thumbnailImage: '',
  //   thumbnailImageAlt: '',
  // }
  {
    folder: "on-javascript-typescript",
    date: "2025-09-23",
    title: "On JavaScript & TypeScript",
    description: "Snippets and tips on JavaScript and TypeScript.",
    thumbnail: false,
    thumbnailImage: "",
    thumbnailImageAlt: "",
  },
  {
    folder: "on-css-scss-styling",
    date: "2025-09-24",
    title: "On CSS/SCSS & Styling",
    description: "Snippets and tips on CSS/SCSS and styling in general.",
    thumbnail: false,
    thumbnailImage: "",
    thumbnailImageAlt: "",
  },
  {
    folder: "on-how-to-remember-what-you-read",
    date: "2025-09-19",
    title: "On How to Remember What You Read: The 5 Levels of Reading",
    description: "A system to never forget what you read.",
    thumbnail: false,
    thumbnailImage: "",
    thumbnailImageAlt: "",
  },
  {
    folder: "on-story",
    date: "2025-09-19",
    title: "On Story: Structure, Elements & Shapes",
    description: "Best story wins.",
    thumbnail: false,
    thumbnailImage: "",
    thumbnailImageAlt: "",
  },
  {
    folder: "on-the-most-profound-moment-in-gaming-history",
    date: "2025-09-19",
    title: "On the Most Profound Moment In Gaming History",
    description: "An incredible conversation about information, the internet, Fake News, VR, AI, censorship, evolution, and free will. Years (maybe decades) ahead of its time.",
    thumbnail: false,
    thumbnailImage: "",
    thumbnailImageAlt: "",
  },
  // {
  //   folder: 'on-python',
  //   date: '2025-05-23',
  //   title: 'On Python',
  //   description: 'Snippets and tips on Python.',
  //   thumbnail: false,
  //   thumbnailImage: '',
  //   thumbnailImageAlt: '',
  // },
  // {
  //   folder: 'on-terminals-clis',
  //   date: '2025-04-15',
  //   title: 'On Terminals & CLIs',
  //   description: 'Snippets and tips on Terminals and CLIs.',
  //   thumbnail: false,
  //   thumbnailImage: '',
  //   thumbnailImageAlt: '',
  // },
  // {
  //   folder: 'on-react-next',
  //   date: '2025-04-15',
  //   title: 'On React & Next.js',
  //   description: 'Snippets and tips on React and Next.js.',
  //   thumbnail: false,
  //   thumbnailImage: '',
  //   thumbnailImageAlt: '',
  // },
  // {
  //   folder: 'on-vue-nuxt',
  //   date: '2025-04-15',
  //   title: 'On Vue & Nuxt',
  //   description: 'Snippets and tips on Vue and Nuxt.',
  //   thumbnail: false,
  //   thumbnailImage: '',
  //   thumbnailImageAlt: '',
  // },
  {
    folder: 'on-markdown',
    date: '2020-05-14',
    title: 'On Markdown',
    description: 'A complete guide on Markdown syntax.',
    thumbnail: false,
    thumbnailImage: '',
    thumbnailImageAlt: '',
  },
  {
    folder: "hello-universe",
    date: "2020-04-02",
    title: "Hello, Universe!",
    description: "An origin story.",
    thumbnail: false,
    thumbnailImage: "",
    thumbnailImageAlt: "",
  },
];
