// Notes appear according to date specified.
const notes = [
  // {
  //   folder:'folder-name',
  //   date: 'YYYY-MM-DD',
  //   title: 'Note Title',
  //   description: 'Description of the note.',
  //   thumbnail: false,
  //   thumbnailImage: '',
  //   thumbnailImageAlt: '',
  // }
  {
    folder: "on-javascript-typescript",
    date: "2024-11-29",
    title: "On JavaScript & TypeScript",
    description: "Snippets and tips on JavaScript and TypeScript.",
    thumbnail: false,
    thumbnailImage: "",
    thumbnailImageAlt: "",
  },
  {
    folder: "on-css-scss-styling",
    date: "2024-11-29",
    title: "On CSS/SCSS & Styling",
    description: "Snippets and tips on CSS/SCSS and styling in general.",
    thumbnail: false,
    thumbnailImage: "",
    thumbnailImageAlt: "",
  },
  // {
  //   folder: 'on-python',
  //   date: '2025-04-15',
  //   title: 'On Python',
  //   description: 'Snippets and tips on Python.',
  //   thumbnail: false,
  //   thumbnailImage: '',
  //   thumbnailImageAlt: '',
  // },
  // {
  //   folder: 'on-terminals-clis',
  //   date: '2025-04-15',
  //   title: 'On Terminals & CLIs',
  //   description: 'Snippets and tips on Terminals and CLIs.',
  //   thumbnail: false,
  //   thumbnailImage: '',
  //   thumbnailImageAlt: '',
  // },
  // {
  //   folder: 'on-react-next',
  //   date: '2025-04-15',
  //   title: 'On React & Next.js',
  //   description: 'Snippets and tips on React and Next.js.',
  //   thumbnail: false,
  //   thumbnailImage: '',
  //   thumbnailImageAlt: '',
  // },
  // {
  //   folder: 'on-vue-nuxt',
  //   date: '2025-04-15',
  //   title: 'On Vue & Nuxt',
  //   description: 'Snippets and tips on Vue and Nuxt.',
  //   thumbnail: false,
  //   thumbnailImage: '',
  //   thumbnailImageAlt: '',
  // },
  {
    folder: 'on-markdown',
    date: '2020-05-14',
    title: 'On Markdown',
    description: 'A complete guide on Markdown syntax.',
    thumbnail: false,
    thumbnailImage: '',
    thumbnailImageAlt: '',
  },
  {
    folder: "hello-universe",
    date: "2020-04-02",
    title: "Hello, Universe!",
    description: "An origin story.",
    thumbnail: false,
    thumbnailImage: "",
    thumbnailImageAlt: "",
  },
];
